name=WS25QxxFlash
version=0.0.0
author=mumanchu <info@muman.ch>
maintainer=mumanchu <info@muman.ch>
sentence=Library for all Winbond SPI Flash memory chips, WS25Q10..W25Q512
paragraph=**PRELIMINARY**
category=Data Storage
includes=WS25QxxFlash.h
url=https://github.com/mumanchu/WS25QxxFlash
architectures=*

