name=W25QxxFlash
version=1.0.1
author=mumanchu <info@muman.ch>
maintainer=mumanchu <info@muman.ch>
sentence=Library for all Winbond SPI Flash memory chips, W25Q10..W25Q512
paragraph=
category=Data Storage
includes=W25QxxFlash.h
url=https://github.com/mumanchu/W25QxxFlash
architectures=*

