name=W25QxxFlash
version=1.0.2
author=mumanchu
maintainer=mumanchu <info@muman.ch>
sentence=Library for SPI Flash memory chips, 1..512Mbits
paragraph=
category=Data Storage
includes=W25QxxFlash.h
url=https://github.com/mumanchu/W25QxxFlash
architectures=*

